config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"

  resources :articles
  resources :users, only: [:show, :index]
  resources :messages, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :subscribtions, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  belongs_to :replied_to, class_name: "Message", optional: true
end

app/models/subscribtion.rb
class Subscribtion < ApplicationRecord
  belongs_to :recepient, class_name: "User"
  belongs_to :subscriber, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :articles, dependent: :destroy

  has_many :sent_subscribtions, class_name: "Subscribtion", foreign_key: :subscriber_id,
    inverse_of: :recepient, dependent: :destroy
  has_many :received_subscribtions, class_name: "Subscribtion", foreign_key: :recepient_id,
    inverse_of: :subscriber, dependent: :destroy
  
  has_many :subscribed_users, through: :received_subscribtions, source: :subscriber
  has_many :subscribed_to_users, through: :sent_subscribtions, source: :recepient

  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from ActionPolicy::Unauthorized, with: :user_not_authorized

  def not_found
    flash[:alert] = "Not Found"
    redirect_to(request.referer || root_path)
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def index
    @article = Article.new
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
    authorize! @article
  end

  def create
    @article = Article.new(article_params)

    if @article.save
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize! @article
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to articles_path }
        format.turbo_stream { render turbo_stream: turbo_stream.update(@article) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! @article
    @article.destroy

    respond_to do |format|
      format.html         { redirect_to articles_url }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@article) }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content).merge(user: current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_messages
  before_action :set_message, only: [:show, :edit, :update, :destroy]


  def index
    @message = Message.new
  end

  def show
  end

  def edit
    authorize! @message
  end

  def update
    authorize! @message

    if @message.update(message_params)
      broadcast_message_updated
      redirect_to messages_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      broadcast_message_created
      redirect_to messages_path
    else
      @messages = Message.all
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! @message

    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_path }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@message) }
    end
  end

  private

  def broadcast_message_created
    Turbo::StreamsChannel.broadcast_render_to(
      [:messages], template: "messages/created", locals: { message: @message }
    )
  end

  def broadcast_message_updated
    Turbo::StreamsChannel.broadcast_render_to(
      [:messages], template: "messages/updated", locals: { message: @message }
    )
  end

  def message_params
    params.require(:message).permit(:content, :replied_to_id).merge(user: current_user)
  end

  def set_messages
    @messages = Message.all.order(created_at: :asc)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/controllers/subscribtions_controller.rb
class SubscribtionsController < ApplicationController
  def create
    @subscribtion = Subscribtion.find_or_create_by(recepient: recepient, subscriber: current_user)

    redirect_back fallback_location: root_path
  end

  def destroy
    @subscribtion = Subscribtion.find(params[:id])
    @subscribtion.destroy

    redirect_back fallback_location: root_path
  end

  private

  def recepient
    User.find_by id: params[:subscribtion][:recepient_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @subscribtion = Subscribtion.find_or_initialize_by(recepient: @user, subscriber: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.slim
.container
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    - if user_signed_in?
      li.nav-item
        = link_to "All Articles", articles_path, class: "nav-link #{yield :articles}", data: { turbo: true }
      li.nav-item
        = link_to "All Users", users_path, class: "nav-link #{yield :users}", data: { turbo: true }
      li.nav-item
        = link_to "Chat", messages_path, class: "nav-link #{yield :messages}", data: { turbo: true }
      li.nav-item
        = button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link", id: "Sign out"
    -else 
      li.nav-item
        = link_to "Sign In", "#", class: "nav-link", id: "Sign in"
  </ul>

app/views/articles/_add_article_button.html.slim
= turbo_frame_tag Article.new do
  = link_to "New", new_article_path, class: "btn btn-outline-primary"

app/views/articles/_article.html.slim
= turbo_frame_tag article do
  hr
  article
    = link_to article.title, article, data: { turbo: true, turbo_frame: "_top" }
    - if allowed_to?(:edit?, article)
      = link_to "Edit", edit_article_path(article), class: "btn btn-secondary"
    - if allowed_to?(:destroy?, article)
      = link_to "Destroy", article, class: "btn btn-danger", data: { turbo: true, turbo_method: :delete }

app/views/articles/_form.html.slim
= turbo_frame_tag article do
  = simple_form_for(article) do |f|
    .form-inputs
      = f.input :title
      = f.input :content
    .form-actions
      = f.button :submit, 'Submit', class: "btn btn-primary"

app/views/articles/create.turbo_stream.erb
<%= turbo_stream.replace Article.new, partial: 'add_article_button' %>
<%= turbo_stream.before Article.new, partial: 'article', locals: { article: @article } %>

app/views/articles/edit.html.slim
h2 Edit article
= render "form", article: @article
br
div
  = link_to "Show", article_path, data: { turbo: true }

app/views/articles/index.html.slim
= content_for(:articles) { "active" }

h2 Articles
= render @articles
= turbo_frame_tag @article do
  = render "add_article_button"

app/views/articles/new.html.slim
h2 New article
= render "form", article: @article
br

app/views/articles/show.html.slim
h2 = @article.title
div Content: #{@article.content}
div Author: #{@article.user.email}

div
  - if allowed_to?(:edit?, @article)
    = link_to "Edit", edit_article_path(@article), class: "btn btn-link", data: { turbo: true }
  - if allowed_to?(:destroy?, @article)
    = button_to "Destroy", @article, method: :delete, class: "btn btn-link"

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title Hotwire
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  </head>

  body
    .container
      = render 'navbar'
      br
      .row
        .col-md-6.offset-md-3
          = yield

app/views/messages/_form.html.slim
= turbo_frame_tag @message do
  = simple_form_for(@message) do |f|
    .form-inputs
      = f.input :content, label: false
      = f.hidden_field :replied_to_id, value: nil, data: { messages_target: "repliedToId" }
    .form-actions
      = f.button :submit, 'Submit', class: "btn btn-primary"

app/views/messages/_message.html.slim
hr
div
  - if message.replied_to.present?
    div
      strong
        |Replied to:
      i class="js-reply-to-message-#{message.replied_to.id}"
        = message.replied_to.content
  strong = message.user.email
  |: 
  span.content
    = message.content
  span data-message-id="#{message.id}" data-action="click->messages#reply" class="btn btn-secondary"
    |  Reply
  span
    - if allowed_to?(:edit?, message)
      = link_to "Edit", edit_message_path(message)
	span
		- if allowed_to? :destroy?, message
			= link_to "Destroy", message, data: { turbo: true, turbo_method: :delete }

app/views/messages/_reply.html.slim
div
  i data-messages-target="repliedToText"
div
  = button_tag "Cancel reply", type: :button, data: { messages_target: "removeReplyButton", action: "click->messages#removeReply" }, class: "hidden"

app/views/messages/_show_message.html.slim
= turbo_frame_tag message, src: message_path(message)

app/views/messages/created.turbo_stream.erb
<%= turbo_stream.before Message.new, partial: 'messages/show_message', locals: { message: message } %>

app/views/messages/edit.html.slim
= render "form"

app/views/messages/index.html.slim
= content_for(:messages) { "active" }

= turbo_stream_from(:messages)

div data-controller="messages"
  - @messages.each do |message|
    = turbo_frame_tag message do
      = render message
  = render "form"
  = render "reply"

app/views/messages/show.html.slim
= turbo_frame_tag @message do
  = render @message

app/views/messages/updated.turbo_stream.erb
<%= turbo_stream.replace message, partial: 'messages/show_message', locals: { message: message } %>
<%= turbo_stream.replace_all ".js-reply-to-message-#{message.id}", message.content %>

app/views/users/_subscribe_buttons.html.erb
<%= button_tag(
  'Subscribe',
  {
    data: {
      reflex: "click->SubscribtionsReflex#subscribe",
      recepient_id: subscribtion.recepient_id
    },
    class: "btn btn-primary",
    type: :button
  }
) unless subscribtion.persisted?
%>
<%= button_tag(
  'Unsubscribe',
  {
    data: {
      subscribtion_id: subscribtion.id,
      subscribe_buttons_target: 'unsubscribeButton',
      action: "click->subscribe-buttons#unsubscribe"
    },
    class: "btn btn-danger",
    type: :button
  }
) if subscribtion.persisted?
%>

app/views/users/_user.html.slim
div
  = link_to user.email, user, data: { turbo: true }

app/views/users/index.html.slim
= content_for(:users) { "active" }

h2 Users
= render @users

app/views/users/show.html.slim
h2 = @user.email
div#subscribe-buttons data-controller="subscribe-buttons"
  = render(partial: "users/subscribe_buttons", locals: {subscribtion: @subscribtion})